<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
      name="viewport"
    />
    <meta content="ie=edge" http-equiv="X-UA-Compatible" />
    <title>Document</title>
  </head>
  <body>
    <script type="module">
      import MyPromise from "./MyPromise.js";
      const p1 = MyPromise.resolve(1);
      const p2 = new MyPromise((resolve) => {
        setTimeout(() => resolve(2), 1000);
      });
      const p3 = new MyPromise((resolve) => {
        setTimeout(() => resolve(3), 3000);
      });

      const p4 = MyPromise.reject("err4");
      const p5 = MyPromise.reject("err5");
      // 1. 所有的Promise都成功了
      // const p11 = MyPromise.all([p1, p2, p3])
      //   .then(console.log) // [ 1, 2, 3 ]
      //   .catch(console.log);

      // // 2. 有一个Promise失败了
      // const p12 = MyPromise.all([p1, p2, p5])
      //   .then(console.log)
      //   .catch(console.log);
      // // 3. 有两个Promise失败了，可以看到最终输出的是err4，第一个失败的返回值
      // const p13 = MyPromise.all([p1, p4, p5])
      //   .then(console.log)
      //   .catch(console.log); // err4

      // const p = MyPromise.race([p3,p2]).then(console.log,console.log)



      const any = MyPromise.any([p4,p2]).then(console.log,console.log)
    </script>
  </body>
</html>
